### PR TITLE
387 fix splash screen

### LINKED ISSUE #387: Bug in SplashViewModel
#### Description:
A bug with using coroutines in `SplashViewModel`.
The view model keeps running even though `onCleared` was called. This is because `GlobalScope` was used.

#### Solution:
Use lifecycle aware `viewModelScope`. It will cancel `delay()`. Remove `async().await()` and change dispatcher from `launch()` instead. For further improvement change methods in `ResourcesInitializer` to suspend and check for `scope.isActive` on each loop of `moveFolder()`.

#### To reproduce:
After starting the app and clicking the back button for three times this is what happens (The splashscreen delay was increased to 10 seconds)

#### Logcat:
```
2020-08-05 16:30:21.991 10152-10152/com.aconno.sensorics.dev E/SplashViewModel: -86 Viewmodel in Thread[main,5,main]
2020-08-05 16:30:22.006 10152-10152/com.aconno.sensorics.dev E/SplashViewModel$initApp: -86 Globalscope launch in Thread[main,5,main]
2020-08-05 16:30:22.007 10152-10221/com.aconno.sensorics.dev E/SplashViewModel$initApp: -86 Globalscope async in Thread[DefaultDispatcher-worker-1,5,main]
2020-08-05 16:30:23.264 10152-10152/com.aconno.sensorics.dev E/SplashViewModel: -86 Viewmodel is cleared
2020-08-05 16:30:24.110 10152-10152/com.aconno.sensorics.dev E/SplashViewModel: -32 Viewmodel in Thread[main,5,main]
2020-08-05 16:30:24.126 10152-10152/com.aconno.sensorics.dev E/SplashViewModel$initApp: -32 Globalscope launch in Thread[main,5,main]
2020-08-05 16:30:24.126 10152-10221/com.aconno.sensorics.dev E/SplashViewModel$initApp: -32 Globalscope async in Thread[DefaultDispatcher-worker-1,5,main]
2020-08-05 16:30:25.964 10152-10152/com.aconno.sensorics.dev E/SplashViewModel: -32 Viewmodel is cleared
2020-08-05 16:30:26.178 10152-10152/com.aconno.sensorics.dev E/SplashViewModel: -79 Viewmodel in Thread[main,5,main]
2020-08-05 16:30:26.195 10152-10152/com.aconno.sensorics.dev E/SplashViewModel$initApp: -79 Globalscope launch in Thread[main,5,main]
2020-08-05 16:30:26.196 10152-10221/com.aconno.sensorics.dev E/SplashViewModel$initApp: -79 Globalscope async in Thread[DefaultDispatcher-worker-1,5,main]
2020-08-05 16:30:27.460 10152-10152/com.aconno.sensorics.dev E/SplashViewModel: -79 Viewmodel is cleared
2020-08-05 16:30:32.014 10152-10152/com.aconno.sensorics.dev E/SplashViewModel$initApp: -86 Continue after Splashscreen
2020-08-05 16:30:34.175 10152-10152/com.aconno.sensorics.dev E/SplashViewModel$initApp: -32 Continue after Splashscreen
2020-08-05 16:30:36.242 10152-10152/com.aconno.sensorics.dev E/SplashViewModel$initApp: -79 Continue after Splashscreen
```

### PR DESCRIPTION
**Pull request by pascaldornfeld**
**Description**
Removed deprecated `ViewModelProviders.of`.
Fixed bad usage of coroutine in `SplashViewModel`.
Added tests for `ResourcesInitializerImpl`.

**Issues to solve**
Fixes #387

### CODE REVIEW

File: data/src/main/java/com/aconno/sensorics/data/repository/ResourcesInitializerImpl.kt [hunk 1]
```diff
@@ -2,61 +2,72 @@ package com.aconno.sensorics.data.repository
...
     }
 
-    private fun moveFolder(folderName: String) {
-        assets.list(folderName)?.let { fileList ->
-            if (fileList.isEmpty()) {
-                Timber.i("$folderName + --")
-                copyFile(folderName)
+    @Throws(IOException::class)
+    private fun copyAssetPathToCache(assetPath: String) {
+        assets.list(assetPath)?.let { elementsInPath ->
```
Comment (borna-mdn) [inline data/src/main/java/com/aconno/sensorics/data/repository/ResourcesInitializerImpl.kt:34]: Rename this to `assetsManager`.
